# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51f027de6ece5e49bfa06099069f420552e4dd6d5f07781d76bca0b3b8a3b1825d06d185a0a45e8b3cab92298f440bbbe06e71894e87f2f9c33cd21e11a2cb19

test:
  secret_key_base: bd1acde535ae7a69848f06be38b160dfa55c6f6a053c89d23a3ffdf69ebf52eb0cf207e2220a922be677c3d6546c4c5c4646de86a2cb567dfa0875067ed28a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
